TRAINING_DATA = [
    ("feed bruno at 8 am", "feeding"),
    ("give luna food at 6 pm", "feeding"),
    ("serve breakfast to max", "feeding"),
    ("dinner for bella", "feeding"),
    ("walk bruno at 7 am", "walking"),
    ("take max outside for a walk", "walking"),
    ("evening walk with luna", "walking"),
    ("give bruno medicine at 8 pm", "medication"),
    ("give luna her pill", "medication"),
    ("medcine for max at night", "medication"),
    ("apply medication to bella", "medication"),
    ("brush luna today", "grooming"),
    ("groom max on friday", "grooming"),
    ("bath for bruno", "grooming"),
    ("vet appointment for luna at 3 pm", "appointment"),
    ("doctor visit for max", "appointment"),
    ("schedule checkup for bella", "appointment"),
    ("play with bruno after lunch", "play"),
    ("playtime for luna", "play"),
    ("throw ball for max", "play"),
    ("random unclear text", "unknown"),
    ("my pet needs care", "unknown"),
    ("do something tomorrow", "unknown"),
]